language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="KittyInterpreter"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
#   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - source install.sh

install:
   - arduino --install-library "ArduinoSTL","ArduinoUnit"

script:
   - build_platform mega2560

# Generate and deploy documentation
#after_success:
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)