language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="KittyInterpreter"
     - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/mattheuslee/travis-ci-arduino/kitty/install.sh)
   - pip install --user cpp-coveralls

install:
   - arduino --install-library "ArduinoSTL","ArduinoUnit","ArduinoLog"

script:
   - build_platform mega2560
   - git clone https://github.com/mmurdoch/arduinounit.git
   - make -B test

# Generate and deploy documentation
after_success:
   - make -B coverage
   - coveralls --exclude arduinounit --exclude test --gcov-options '\-lp'
   - rm -r -f /home/travis/build/mattheuslee/KittyInterpreter/arduinounit/ 
   - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
   - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)

